export const SYSTEM_CONSTANT = {
  APP_NAME: "CMS",
  ACCESS_TOKEN: "access_token",
  REFRESH_TOKEN: "refresh_token",
  SITE_CONFIG_TYPE: {
    TOPBAR: "topbar",
    CONTACT_ICON: "contactIcon",
    WHY_NOT: "whyNot",
    MAIN_LOGO: "mainLogo",
    SUB_LOGO: "subLogo",
    FAVICON: "favicon",
    PRIMARY_COLOR: "primaryColor",
    WEBSITE_INFO: "websiteInfo",
    SEO_INFO: "seoInfo",
    CONTACT_INFO_NAME: "contactInfoName",
    CONTACT_INFO_ADDRESS: "contactInfoAddress",
    CONTACT_INFO_TAX_CODE: "contactInfoTaxCode",
    CONTACT_INFO_PHONE: "contactInfoPhone",
    CONTACT_INFO_EMAIL: "contactInfoEmail",
    CONTACT_INFO_LAT: "contactInfoLat",
    CONTACT_INFO_LNG: "contactInfoLng",
  },
};
